### ISSUE TITLE
how to reuse write text on image

### ISSUE THREAD

**Issue by sajjadjaved01** [burhanrashid52/PhotoEditor#106]
Hi, i have a drawing canvas & i want text to appear to my canvas. i have did that but after clicking on done, gives me error 

    Process: smartboard.fyp.com.smartapp, PID: 7731
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup)' on a null object reference
        at com.raed.drawingview.DrawingView.getLayout(DrawingView.java:712)
        at com.raed.drawingview.DrawingView.addText(DrawingView.java:663)
        at com.raed.drawingview.DrawingView.addText(DrawingView.java:650)
        at smartboard.fyp.com.smartapp.MainActivity$20.onDone(MainActivity.java:736)
        at smartboard.fyp.com.smartapp.TextEditorDialogFragment$2.onClick(TextEditorDialogFragment.java:116)
        at android.view.View.performClick(View.java:5210)
        at android.view.View$PerformClick.run(View.java:21328)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by burhanrashid52** [comment]
How did you add text on canvas?

**Comment by sajjadjaved01** [comment]
same as you are doing in this sample app, i'm using this [lib](https://github.com/Raed-Mughaus/DrawingView) for drawing on that designView i want this to show text.

**Comment by burhanrashid52** [comment]
It's hard to say anything from this log. Can you post your code how you are doing this?

**Comment by burhanrashid52** [comment]
closing due to inactivity
