### ISSUE TITLE
Image not getting saved(IndexOutOfBoundsException)

### ISSUE THREAD

**Issue by naiksan** [burhanrashid52/PhotoEditor#123]
2018-12-27 16:40:09.122 32655-5416/com.example W/System.err: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
2018-12-27 16:40:09.122 32655-5416/com.example W/System.err:     at java.util.ArrayList.get(ArrayList.java:437)
2018-12-27 16:40:09.122 32655-5416/com.example W/System.err:     at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3624)
2018-12-27 16:40:09.122 32655-5416/com.example W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4110)
2018-12-27 16:40:09.122 32655-5416/com.example W/System.err:     at android.view.View.draw(View.java:20087)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at android.view.View.buildDrawingCacheImpl(View.java:19484)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at android.view.View.buildDrawingCache(View.java:19350)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at android.view.View.getDrawingCache(View.java:19186)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at android.view.View.getDrawingCache(View.java:19137)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at ja.burhanrashid52.photoeditor.PhotoEditor$5$1.doInBackground(PhotoEditor.java:653)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at ja.burhanrashid52.photoeditor.PhotoEditor$5$1.doInBackground(PhotoEditor.java:633)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2018-12-27 16:40:09.123 32655-5416/com.example W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2018-12-27 16:40:09.124 32655-5416/com.example W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-12-27 16:40:09.124 32655-5416/com.example D/PhotoEditor: Failed to save File

**Comment by naiksan** [comment]
Hi @burhanrashid52  please follow these steps.
1. Save an empty bitmap.
2. Set the URI of above image to the photoEditorView.
 photoEditorView.source.setImageURI(IMAGE_URI) 
3. Add bitmap using 
photoEditor.addImage(bitmap)
4. Increase the size of the inserted bitmap such that it crosses the photoEditorView's boundary.
5. Save
6. If it saves successfully then try multiple time as sometimes it saves and sometimes does not.

**Comment by atominvention** [comment]
I have this issue too, seems pretty random, with the sample app
1. open an image
2. add a few Text Label, adjust the size and rotation of those text labels
3. save

sometimes it will save failed with the IndexOutOfBoundsException as mentioned above

**Comment by burhanrashid52** [comment]
Thanks for the step. Let me check

**Comment by huynhhoa** [comment]
Hi Burhanrashid, it's still happening sir, what's should I do ?

**Comment by jastip** [comment]
I think I found the bug, when the setTransparencyEnabled(false) in the SaveSettings, sometimes it will fail to getDrawingCache(). But if I set setTransparencyEnabled(true) it will never happened.

**Comment by jastip** [comment]
I also experienced with this bug, not always happen, but intermitent. IMHO since saving the file using AsyncTask, maybe the drawingcache is not yet ready / available to be saved.

**Comment by ThallesLazaro** [comment]
I am still trying to solve this problem, anyone managed to solve?

**Comment by mrgulshanyadav** [comment]
hello Burhanrashid52, I am also getting the same exception, some times it saves some times it does not saves and crashes. Please fix this issue As Soon As Possible. Otherwise, this library is of no use

**Comment by ShaliniRamasamy** [comment]
I am also getting the same exception

**Comment by pragi-karthi** [comment]
I am also getting the same exception,

**Comment by pragi-karthi** [comment]
I am also getting the same exception

**Comment by WonShaw** [comment]
Don't buildDrawingCache in non-ui thread !!! Move your UI-related code to main thread and this error may gone.

**Comment by burhanrashid52** [comment]
This issue is fixed in 1.1.0 release. Reopen this if you are still facing this issue.
