### ISSUE TITLE
Crash my application on saving. IndexOutOfBoundsException: Index: 1, size: 0

### ISSUE THREAD

**Issue by Salman-Hameed** [burhanrashid52/PhotoEditor#135]

**Comment by burhanrashid52** [comment]
Can you please share the steps to reproduce this issue?

**Comment by Salman-Hameed** [comment]
it do not crash every time but sometimes crash on saving bitmap, here is my code to save bitmap.

        mPhotoEditor.saveAsBitmap(object : OnSaveBitmap {
            override fun onFailure(e: Exception?){
                Toast.makeText(this@PhotoEditorActivity, "Image not saved !!!", Toast.LENGTH_LONG).show()
            }

            override fun onBitmapReady(saveBitmap: Bitmap?) {
           
                    **BitmapHelper.getInstance().resultant_bitmap = saveBitmap**
              
            }

        })

**Comment by jastip** [comment]
I also experienced this error. I think the error is when to get drawing cache from parentView,

` W/System.err: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
2019-07-17 09:57:26.477 1888-5009/com.jastip.jastiperapp W/System.err:     at java.util.ArrayList.get(ArrayList.java:437)
2019-07-17 09:57:26.477 1888-5009/com.jastip.jastiperapp W/System.err:     at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3816)
2019-07-17 09:57:26.477 1888-5009/com.jastip.jastiperapp W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4330)
2019-07-17 09:57:26.477 1888-5009/com.jastip.jastiperapp W/System.err:     at android.view.View.draw(View.java:21743)
2019-07-17 09:57:26.477 1888-5009/com.jastip.jastiperapp W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
2019-07-17 09:57:26.477 1888-5009/com.jastip.jastiperapp W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
2019-07-17 09:57:26.477 1888-5009/com.jastip.jastiperapp W/System.err:     at android.view.View.buildDrawingCacheImpl(View.java:21140)
2019-07-17 09:57:26.477 1888-5009/com.jastip.jastiperapp W/System.err:     at android.view.View.buildDrawingCache(View.java:21006)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at android.view.View.getDrawingCache(View.java:20842)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at android.view.View.getDrawingCache(View.java:20793)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at ja.burhanrashid52.photoeditor.PhotoEditor$5$1.doInBackground(PhotoEditor.java:670)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at ja.burhanrashid52.photoeditor.PhotoEditor$5$1.doInBackground(PhotoEditor.java:650)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-07-17 09:57:26.478 1888-5009/com.jastip.jastiperapp D/PhotoEditor: Failed to save File
2019-07-17 09:57:26.478 1888-1888/com.jastip.jastiperapp E/PhotoViewerActivity: Index: 1, Size: 0`

**Comment by burhanrashid52** [comment]
This issue is fixed in 1.1.0 release. Reopen this if you are still facing this issue.
