### ISSUE TITLE
IndexOutOfBoundsException: Invalid index 1, size is 0

### ISSUE THREAD

**Issue by wifirevaithi** [burhanrashid52/PhotoEditor#197]
Hi,

  i'm Getting IndexOutOfBoundsException: Invalid index 1, size is 0..
Steps:
1.Select Image
2.Select Emoji
3.Scale The Emoji Larger and click Save
It'll Crash....please Give Me a Solution...................

**Comment by paoloPastorini** [comment]
Try to tap the sticker to make dissapear the frame, then save. I was having that problem to... if is the same issue then before saving you must clear all the frames of the stickers and/or emojis to save properly. I hope works for you

**Comment by hamza-ahmed** [comment]
im also get this problem , i cant find solution  java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3626)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.buildDrawingCacheImpl(View.java:19499)
        at android.view.View.buildDrawingCache(View.java:19365)
        at android.view.View.getDrawingCache(View.java:19201)
        at android.view.View.draw(View.java:19956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at android.view.View.draw(View.java:20104)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at android.view.View.draw(View.java:20104)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at com.android.internal.policy.DecorView.draw(DecorView.java:784)
        at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3532)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3431)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3187)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2556)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1527)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7406)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1044)
        at android.view.Choreographer.doCallbacks(Choreographer.java:839)
        at android.view.Choreographer.doFrame(Choreographer.java:774)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1030)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by MudassirAziz** [comment]
Hi dear !
Here is a Good news!
I have just resolved that flaw by using 
mPhotoEditorView.setTransitionVisibility(View.GONE); 
before mPhotoEditor.saveAsFile()   method.

**Comment by hamza-ahmed** [comment]
Hi dear, im deleted thus library and use other one , im post this issue
multiple times without any response 😡 , thanks for you

**Comment by VishalTuran** [comment]
> Try to tap the sticker to make dissapear the frame, then save. I was having that problem too... if is the same issue then before saving you must clear all the frames of the stickers and/or emojis to save properly. I hope works for you

How to clear the frames.Can you please help with the code

**Comment by MudassirAziz** [comment]
just write before saving the image
mPhotoEditorView.setTransitionVisibility(View.GONE);

**Comment by VishalTuran** [comment]
> just write before saving the image
> mPhotoEditorView.setTransitionVisibility(View.GONE);

Still not working.Do you have any other solution

**Comment by VishalTuran** [comment]
I think I got the solution.
Before saving your image just add this line of code:
photoEditor.clearHelperBox();

**Comment by VishalTuran** [comment]
After looking at few methods to resolve the problem.I think the best solution is
1) Get Bitmap from mPhotoEditorView using the following code:

                                mPhotoEditorView.setDrawingCacheEnabled(true);

                                mPhotoEditorView.buildDrawingCache();

                                Bitmap bm =  mPhotoEditorView.getDrawingCache();
2) Then save this bitmap to storage.

**Comment by burhanrashid52** [comment]
This issue is fixed in 1.1.0 release. Let me if you are still facing this issue.
