### ISSUE TITLE
Filter throws Exception

### ISSUE THREAD

**Issue by akwatson** [burhanrashid52/PhotoEditor#210]
**The photo editor throws this exception and is highly repeatable**

Fatal Exception: java.lang.RuntimeException: Could not compile and link shader!
       at android.filterfw.core.ShaderProgram.<init>(ShaderProgram.java:58)
       at android.filterpacks.imageproc.BrightnessFilter.getShaderProgram(BrightnessFilter.java:51)
       at android.filterpacks.imageproc.SimpleImageFilter.updateProgramWithTarget(SimpleImageFilter.java:92)
       at android.filterpacks.imageproc.SimpleImageFilter.process(SimpleImageFilter.java:72)
       at android.filterfw.core.Filter.performProcess(Filter.java:473)
       at android.filterfw.core.FilterFunction.execute(FilterFunction.java:80)
       at android.filterfw.core.FilterFunction.executeWithArgList(FilterFunction.java:97)
       at android.media.effect.SingleFilterEffect.apply(SingleFilterEffect.java:73)
       at ja.burhanrashid52.photoeditor.ImageFilterView.applyEffect(ImageFilterView.java:263)
       at ja.burhanrashid52.photoeditor.ImageFilterView.onDrawFrame(ImageFilterView.java:100)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

Here is one device that it occurs on;
![Screenshot_20191211-143232](https://user-images.githubusercontent.com/11513214/70658260-3d885780-1c23-11ea-94fb-b17189711cc5.png)

**Comment by NahlaSaadAlDeen** [comment]
@akwatson   is there any solution for this problem,please?
