### ISSUE TITLE
 java.lang.IndexOutOfBoundsException: Index: 1, Size: 0

### ISSUE THREAD

**Issue by hamza-ahmed** [burhanrashid52/PhotoEditor#229]
im also get this problem , i cant find solution  java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3626)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.buildDrawingCacheImpl(View.java:19499)
        at android.view.View.buildDrawingCache(View.java:19365)
        at android.view.View.getDrawingCache(View.java:19201)
        at android.view.View.draw(View.java:19956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at android.view.View.draw(View.java:20104)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at android.view.View.draw(View.java:20104)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20102)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at com.android.internal.policy.DecorView.draw(DecorView.java:784)
        at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3532)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3431)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3187)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2556)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1527)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7406)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1044)
        at android.view.Choreographer.doCallbacks(Choreographer.java:839)
        at android.view.Choreographer.doFrame(Choreographer.java:774)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1030)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

_Originally posted by @hamza-ahmed in https://github.com/burhanrashid52/PhotoEditor/issues/197#issuecomment-582816920_

**Comment by burhanrashid52** [comment]
closing since it's a duplicate

**Comment by hamza-ahmed** [comment]
How you solve that ?
