### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ImageView ja.burhanrashid52.photoeditor.PhotoEditorView.getSource()' on a null object reference

### ISSUE THREAD

**Issue by tubasoft** [burhanrashid52/PhotoEditor#231]
Hi
Thank you for this awesome library

This library used to work for me on another project last year , But this time on new android project (Base on AndroidX) , I get the following error :

> java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ImageView ja.burhanrashid52.photoeditor.PhotoEditorView.getSource()' on a null object reference

I import your sample editor into my main project , When i try to load the editor from any activity , It get me the same error

I already added the EditImageActivity in my manifast file

> <activity
>             android:name=".img.EditImageActivity"
>             android:screenOrientation="portrait"
>             android:theme="@style/AppTheme.NoActionBar" />
> 

The simple code is it :
        

> PhotoEditorView mPhotoEditorView = findViewById(R.id.photoEditorView);
> Typeface mEmojiTypeFace = Typeface.createFromAsset(getAssets(), "emojione-android.ttf");
> PhotoEditor mPhotoEditor = new PhotoEditor.Builder(this, mPhotoEditorView)
>    .setPinchTextScalable(true)
>    .setDefaultEmojiTypeface(mEmojiTypeFace)
>    .build();
> 

        
The error output is :

> 2020-02-09 19:47:38.415 8708-8708/com.prjtemp42.android E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.prjtemp42.android, PID: 8708
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.prjtemp42.android/com.prjtemp42.android.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ImageView ja.burhanrashid52.photoeditor.PhotoEditorView.getSource()' on a null object reference
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
>         at android.app.ActivityThread.-wrap12(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:154)
>         at android.app.ActivityThread.main(ActivityThread.java:6077)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
>      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ImageView ja.burhanrashid52.photoeditor.PhotoEditorView.getSource()' on a null object reference
>         at ja.burhanrashid52.photoeditor.PhotoEditor$Builder.<init>(PhotoEditor.java:866)
>         at com.prjtemp42.android.MainActivity.onCreate(MainActivity.java:234)
>         at android.app.Activity.performCreate(Activity.java:6662)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
>         at android.app.ActivityThread.-wrap12(ActivityThread.java) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
>         at android.os.Handler.dispatchMessage(Handler.java:102) 
>         at android.os.Looper.loop(Looper.java:154) 
>         at android.app.ActivityThread.main(ActivityThread.java:6077) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

Any help will be great 

Thank you 👍

**Comment by shilpa-1234** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void ja.burhanrashid52.photoeditor.PhotoEditor.setFilterEffect(ja.burhanrashid52.photoeditor.PhotoFilter)' on a null object reference
        at com.burhanrashid52.photoeditor.EditImageActivity.onFilterSelected(EditImageActivity.java:486)
        at com.burhanrashid52.photoeditor.filters.FilterViewAdapter$ViewHolder$1.onClick(FilterViewAdapter.java:66)

**Comment by karims** [comment]
I got the same error. Then, before running `Builder`, I added image to the photoEditorView like this :

```
photoEditorView.getSource().setImageURI(imageUri);
```

It worked fine.

**Comment by burhanrashid52** [comment]
Closing due to no activity.
