### ISSUE TITLE
Filter Error: java.lang.RuntimeException: Error executing ShaderProgram!

### ISSUE THREAD

**Issue by Carlos2927** [burhanrashid52/PhotoEditor#232]
java.lang.RuntimeException: Error executing ShaderProgram!
        at android.filterfw.core.ShaderProgram.process(ShaderProgram.java:132)
        at android.filterfw.core.Program.process(Program.java:32)
        at android.filterpacks.imageproc.CrossProcessFilter.process(CrossProcessFilter.java:116)
        at android.filterfw.core.Filter.performProcess(Filter.java:483)
        at android.filterfw.core.FilterFunction.execute(FilterFunction.java:80)
        at android.filterfw.core.FilterFunction.executeWithArgList(FilterFunction.java:97)
        at android.media.effect.SingleFilterEffect.apply(SingleFilterEffect.java:73)
        at ja.burhanrashid52.photoeditor.ImageFilterView.applyEffect(ImageFilterView.java:263)
        at ja.burhanrashid52.photoeditor.ImageFilterView.onDrawFrame(ImageFilterView.java:100)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

Test Device: Google Pixel 3A
Test Photo:
![IMG_20200112_091108](https://user-images.githubusercontent.com/12493233/76483023-e1ff7d00-6450-11ea-8506-e6887b70b1c8.jpg)

**Comment by maximusapp** [comment]
> java.lang.RuntimeException: Error executing ShaderProgram!
> at android.filterfw.core.ShaderProgram.process(ShaderProgram.java:132)
> at android.filterfw.core.Program.process(Program.java:32)
> at android.filterpacks.imageproc.CrossProcessFilter.process(CrossProcessFilter.java:116)
> at android.filterfw.core.Filter.performProcess(Filter.java:483)
> at android.filterfw.core.FilterFunction.execute(FilterFunction.java:80)
> at android.filterfw.core.FilterFunction.executeWithArgList(FilterFunction.java:97)
> at android.media.effect.SingleFilterEffect.apply(SingleFilterEffect.java:73)
> at ja.burhanrashid52.photoeditor.ImageFilterView.applyEffect(ImageFilterView.java:263)
> at ja.burhanrashid52.photoeditor.ImageFilterView.onDrawFrame(ImageFilterView.java:100)
> at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
> at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
> 
> Test Device: Google Pixel 3A
> Test Photo:
> ![IMG_20200112_091108](https://user-images.githubusercontent.com/12493233/76483023-e1ff7d00-6450-11ea-8506-e6887b70b1c8.jpg)

I face some problem. Who can help?

**Comment by satputekuldip** [comment]
`Fatal Exception: java.lang.RuntimeException: Error executing ShaderProgram!
       at android.filterfw.core.ShaderProgram.process(ShaderProgram.java:123)
       at android.filterpacks.imageproc.AutoFixFilter.process(AutoFixFilter.java:260)
       at android.filterfw.core.Filter.performProcess(Filter.java:473)
       at android.filterfw.core.FilterFunction.execute(FilterFunction.java:80)
       at android.filterfw.core.FilterFunction.executeWithArgList(FilterFunction.java:97)
       at android.media.effect.SingleFilterEffect.apply(SingleFilterEffect.java:73)
       at ja.burhanrashid52.photoeditor.ImageFilterView.applyEffect(ImageFilterView.java:263)
       at ja.burhanrashid52.photoeditor.ImageFilterView.onDrawFrame(ImageFilterView.java:100)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1579)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1278)`

Does anyone get the solution...?

**Comment by satputekuldip** [comment]
It's the Resolution some devices can not handle... I resized the image then it worked... If anyone has the solution please share...

**Comment by ankitbatra11** [comment]
I am also facing the same issue. Is there any fix available for this?
