### ISSUE TITLE
 java.lang.IndexOutOfBoundsException: Index: 1, Size: 0

### ISSUE THREAD

**Issue by HritikBhat** [burhanrashid52/PhotoEditor#284]
When the sticker is larger than photoediterview or multiple sticker on photoeditorview...It causing in version 1.1.0

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.digitalvtalks.data, PID: 29899
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3756)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4243)
        at android.view.View.draw(View.java:20346)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
        at android.view.View.buildDrawingCacheImpl(View.java:19720)
        at android.view.View.buildDrawingCache(View.java:19586)
        at android.view.View.getDrawingCache(View.java:19492)
        at android.view.View.getDrawingCache(View.java:19457)
        at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground(PhotoEditor.java:745)
        at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground(PhotoEditor.java:731)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by JSpiner** [comment]
same here

**Comment by JSpiner** [comment]
fixed at [v1.1.1](https://github.com/burhanrashid52/PhotoEditor/releases/tag/v.1.1.1)

**Comment by JSpiner** [comment]
thanks to @burhanrashid52

**Comment by burhanrashid52** [comment]
Fixed in v.1.1.1
