### ISSUE TITLE
ImageView.ScaleType.CENTER_CROP not working properly

### ISSUE THREAD

**Issue by olmur** [burhanrashid52/PhotoEditor#86]
ImageView.ScaleType.CENTER_CROP not working every time. I know this is strange but different photos behaves differently, some of them cropping and some not. Also I was trying to crop them using Glide but when I'm loading image with Glide and than trying to enable brush app crash with the exception 

> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.payphone.android.dev, PID: 11227
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1013)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:980)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:930)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:891)
        at ja.burhanrashid52.photoeditor.BrushDrawingView.onSizeChanged(BrushDrawingView.java:169)
        at android.view.View.sizeChange(View.java:19792)
        at android.view.View.setFrame(View.java:19753)
        at android.view.View.layout(View.java:19656)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Could someone please help with this? My goal is to make picture fill full screen like CENTER_CROP do it.

**Comment by burhanrashid52** [comment]
Are you able to load the image from glide after cropping ?

**Comment by olmur** [comment]
Sorry for the delay. I was not able to enable brush mode when loading image with glide, coz of race condition when Glide loads image async. Also CENTER_CROP was not working coz underlying ImageView has wrap_content value for height, when I changed it to match_parent it's working as expected. After small modification I have no issues with the library, sorry for bothering u and big thanks for such cool library :)

**Comment by jibraniqbal666** [comment]
@olmur could you please tell what modification you have done, my app crashes occasionally with this bug.

**Comment by ankitbatra11** [comment]
@olmur Would it be possible to share the fix for the issue or at least describe the race condition with Glide that leads to this issue?
